[package]
name = "geo"
description = "Geospatial primitives and algorithms"
version = "0.17.1"
authors = ["Corey Farwell <coreyf@rwell.org>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/georust/geo"
documentation = "https://docs.rs/geo/"
readme = "../README.md"
keywords = ["gis", "geo", "geography", "geospatial"]
autobenches = true
edition = "2018"

[badges]
travis-ci = { repository = "georust/geo" }

[dependencies]
num-traits = "0.2"
serde = { version = "1.0", optional = true, features = ["derive"] }
rstar = { version = "0.8" }
geographiclib-rs = { version = "0.2" }
log = "0.4.11"

proj = { version = "0.20.3", optional = true }

geo-types = { version = "0.7.0", features = ["approx", "use-rstar"] }

robust = { version = "0.2.2" }

[features]
use-proj = ["proj"]
proj-network = ["use-proj", "proj/network"]
use-serde = ["serde", "geo-types/serde"]

[dev-dependencies]
approx = "0.4.0"
criterion = { version = "0.3" }
# jts-test-runner is an internal crate which exists only to be part of the geo test suite.
# As such it's kept unpublished. It's in a separate repo primarily because it's kind of large.
jts-test-runner = { git = "https://github.com/georust/jts-test-runner", rev = "3294b9af1d3e64fcc9caf9646a93d0116f7d8321" }
rand = "0.8.0"
serde-xml-rs = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
wkt = "0.8"

[[bench]]
name = "area"
harness = false

[[bench]]
name = "contains"
harness = false

[[bench]]
name = "convex_hull"
harness = false

[[bench]]
name = "concave_hull"
harness = false

[[bench]]
name = "vincenty_distance"
harness = false

[[bench]]
name = "geodesic_distance"
harness = false

[[bench]]
name = "extremes"
harness = false

[[bench]]
name = "euclidean_distance"
harness = false

[[bench]]
name = "rotate"
harness = false

[[bench]]
name = "simplify"
harness = false

[[bench]]
name = "simplifyvw"
harness = false

[[bench]]
name = "frechet_distance"
harness = false
